/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox_treewalk_interpreter;

import org.junit.Test;

public class AppTest {

    @Test
    public void parseExpression() {
        String sourceCode = "(2 - 3) + 5 * 3 / 2 ";
        Scanner scanner = new Scanner(sourceCode);
        Parser parser = new Parser(scanner.scanTokens());
        Expr expression = parser.parse();

        Interpreter interpreter = new Interpreter();
        interpreter.interpret(expression);
    }
}
